import os

stars = [["",0.,0.],]

counter = 0
for i in stars:
    counter += 0.01
    os.makedirs(i[0]+"/Configs")
    with open(i[0]+"/Configs/"+i[0]+".cfg", "w") as f:
        f.write(f'''@Kopernicus:FOR[RealGalacticSystems]
{{
	Body
	{{
		name = {i[0]}
		barycenter = False
		finalizeOrbit = False
		randomMainMenuBody = False
		contractWeight = 5
    	cacheFile = RealGalacticSystems/Cache/{i[0]}.bin
     
	    Template
	    {{
	    	name = Sun
	    }}
	    Properties
	    {{
		    displayName = {i[0]}^N
		    description = Procedurally generated by a python script.
			radius = {i[2]*6.96e8}
	    	mass = {i[1]*1.9891e30}
			rotates = true
	    	rotationPeriod = 
			tidallyLocked = False
			useTheInName = False
	    	selectable = True
			sphereOfInfluence = 1E10
	    }}
	    Orbit
	    {{
			inclination = 0
			eccentricity = 0
			longitudeOfAscendingNode = 0
			argumentOfPeriapsis = 0
			meanAnomalyAtEpoch = {counter}
			epoch = 2000
			color = 1,1,1,1
			nodeColor = 1,1,1,1
			mode = REDRAW_AND_RECALCULATE
			icon = ALL
			cameraSmaRatioBounds = 0.03 25
	    	referenceBody = unknown
		    semiMajorAxis = 10000000000000000
	    }}
		ScaledVersion
		{{
			Light
			{{
				luminosity = 10000
				brightnessCurve
				{{
					key = -0.01573471 0.2 0 0
					key = 0.005 0.2 0 0
					key = 0.01 0 0 0
					key = 0.1 0 0 0
					key = 5.084181 0 0 0
					key = 10 0 0 0
					key = 38.56295 0 0 0
				}}
				IntensityCurve
				{{
					key =	55534 	1.3	0	-5.714E-11
					key =	3500000000 	1.1	-5.714E-11	-4.122E-11
					key =	7000000000 	1.0	-2.061E-11	-2.061E-11
					key =	14000000000 	0.9	-1.030E-11	-1.030E-11
					key =	28000000000 	0.8	-5.152E-12	-5.152E-12
					key =	56000000000 	0.7	-2.576E-12	-2.576E-12
					key =	112000000000 	0.6	-1.288E-12	-1.288E-12
					key =	224000000000 	0.5	-6.441E-13	-6.441E-13
					key =	448000000000 	0.4	-3.220E-13	-3.220E-13
					key =	896000000000 	0.3	-1.610E-13	-1.610E-13
					key =	1792000000000 	0.2	-8.051E-14	-8.051E-14
					key =	3584000000000 	0.1	-4.025E-14	-4.025E-14
					key =	7168000000000 	0	-2.013E-14	0
				}}
				IVAIntensityCurve
				{{
					key =	0 	1.17	0	-5.143E-11
					key =	3500000000 	0.99	-5.143E-11	-3.710E-11
					key =	7000000000 	0.90	-1.855E-11	-1.855E-11
					key =	14000000000 	0.81	-9.274E-12	-9.274E-12
					key =	28000000000 	0.72	-4.637E-12	-4.637E-12
					key =	56000000000 	0.63	-2.319E-12	-2.319E-12
					key =	112000000000 	0.54	-1.159E-12	-1.159E-12
					key =	224000000000 	0.45	-5.797E-13	-5.797E-13
					key =	448000000000 	0.36	-2.898E-13	-2.898E-13
					key =	896000000000 	0.27	-1.449E-13	-1.449E-13
					key =	1792000000000 	0.18	-7.246E-14	-7.246E-14
					key =	3584000000000 	0.09	-3.623E-14	-3.623E-14
					key =   7168000000000 	0	-1.811E-14	0
				}}
				ScaledIntensityCurve
				{{
					key =	0 	1.3	0	-3.429E-07
					key =	583333 	1.1	-3.429E-07	-2.473E-07
					key =	1166667 	1.0	-1.237E-07	-1.237E-07
					key =	2333333 	0.9	-6.183E-08	-6.183E-08
					key =	4666667 	0.8	-3.091E-08	-3.091E-08
					key =	9333333 	0.7	-1.546E-08	-1.546E-08
					key =	18666667 	0.6	-7.729E-09	-7.729E-09
					key =	37333333 	0.5	-3.864E-09	-3.864E-09
					key =	74666667 	0.4	-1.932E-09	-1.932E-09
					key =	149333333 	0.3	-9.661E-10	-9.661E-10
					key =	298666667 	0.2	-4.830E-10	-4.830E-10
					key =	597333333 	0.1	-2.415E-10	-2.415E-10
					key =	1194666667 	0	-1.208E-10	0
				}}
			}}
		}}
  }}
}}
''')
