# RGSStarGenerator.py
# Copyright (C) 2025 Chitak985YT
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.

import os
import AstroToKSP
import requests

selectionString = lambda tmp, str1, str2: tmp[tmp.index(str1)+len(str1):tmp.index(str2,tmp.index(str1))]

# 2.992 log g is 1 G

class Star:
  def __init__(self, name, logGSurfaceGravity, luminositySun, tempK, massSuns, radiusSuns, rotationDays, description="Generated by a Python 3 script from a data array.", SIMBADdesg=None):
    self.name = name
    self.name2 = name.replace(" ","_").replace(".","")  # KSP-friendly name
    self.description = description
    if(logGSurfaceGravity is None):
      self.gravity = None
    else:
      self.gravity = (10**logGSurfaceGravity)/100  # gravity in G
    self.luminosity = luminositySun*1360  # Using Kerbol luminosity as base
    self.ambientTemp = tempK  # HazardousBody ambientTemp value
    self.mass = massSuns*2e30
    self.radius = radiusSuns*6.957e8
    if(type(rotationDays) is type([])):
      self.rotationPeriod = 25.4 * ((rotationDays[0] / 1e9) / 4.603) ** 0.5 * 86400
    else:
      self.rotationPeriod = rotationDays*86400
    if(SIMBADdesg is None):
      self.SIMBADname = name[:]
    else:
      self.SIMBADname = SIMBADdesg

stars = []

print('Enter data or URLs for stars below. Type "stop" when prompted for star URL or name to stop adding stars. When entering information manually, gravity is optional, use "na" when unknown. Type "age" for rotation period if it is unknown to calculate it from age instead.')

counter = 0
while True:
  counter += 1
  q1 = input("[STAR "+str(counter)+"] Enter star URL from stellarcatalog.com: ").lower()
  if(q1 == "stop"):
    break
  if(1):
    tmp = requests.get(q1).text
    q1 = selectionString(tmp,"<meta name='Title' content='&#9733; Star "," | Stellar Catalog'>")
    q3 = float(selectionString(tmp,"Luminosity: <span class='value'>","</span> L"))
    q4 = float(selectionString(tmp,"Temperature: <span class='value'>","</span> K <span class='separator'>|</span> "))
    q5 = float(selectionString(tmp,"<div>Mass: <span class='value'>"," %</span> M<span class='lowerIndex'> Sun</span></div>"))/100
    q7 = [float(selectionString(tmp,"Age: <span class='value'>","</span> billions years "))*100000000]
    q6 = float(selectionString(tmp,"<div>Size: <span class='value'>"," %</span> R<span class='lowerIndex'> Sun</span></div>"))/100
    q8 = selectionString(tmp,"<meta name='description' content='"," '>")
    q9 = selectionString(tmp,"""<strong style='color:#999;'>Other designations of this star</strong><br>
      <span>""",", ")
    print("Automated data retrieval succeeded, data accquired is shown below:\n",[q1,q3,q4,q5,q6,q7,q8,q9])
    stars.append(Star(q1,None,q3,q4,q5,q6,q7,q8,q9))
  try: pass
  except Exception:
    print("Automated retrieval failed. Please enter information manually.")
    q1 = input("[STAR "+str(counter)+"] Enter star name: ").lower()
    if(q1 == "stop"):
      break
    q3 = float(input("[STAR "+str(counter)+"] Enter luminosity in Lsun: "))
    q4 = float(input("[STAR "+str(counter)+"] Enter temperature in K: "))
    q5 = float(input("[STAR "+str(counter)+"] Enter mass in Msun: "))
    q6 = float(input("[STAR "+str(counter)+"] Enter radius in Rsun: "))
    q7 = input("[STAR "+str(counter)+"] Enter rotation period in days: ")
    if(q7 == "age"):
      q7 = float(input("[STAR "+str(counter)+"] Enter age in years: "))
      q7 = [q7]
    q2 = input("[STAR "+str(counter)+"] Enter gravity in log g: ")
    if(q2 == "na"):
      q2 = None
    q9 = input("[STAR "+str(counter)+"] Enter designation to use in SIMBAD if the name provided does not work (use na to skip): ")
    if(q9 == "na"):
      q9 = None
    stars.append(Star(q1,q2,q3,q4,q5,q6,q7,SIMBADdesg=q9))

for i in stars:
  orbit = AstroToKSP.makeKoprnicusOrbit(AstroToKSP.skycoord_to_ksp_orbit(AstroToKSP.getSimbadStar(i.SIMBADname)))
  os.makedirs("RealGalacticSystems/Systems/MilkyWay/Systems/"+i.name2+"/Configs", exist_ok=True)
  if(i.gravity is None):
    gravityThing = ""
  else:
    gravityThing = "\n      geeASL = "+str(i.gravity)
  with open("RealGalacticSystems/Systems/MilkyWay/Systems/"+i.name2+"/Configs/"+i.name2+".cfg", "w") as f:
    f.write(f'''@Kopernicus:FOR[RealGalacticSystems]
{{
  Body
  {{
    name = {i.name2}
    barycenter = False
    finalizeOrbit = False
    randomMainMenuBody = False
    contractWeight = 5
    cacheFile = RealGalacticSystems/Cache/{i.name2}.bin

    Template
    {{
      name = Sun
    }}
    Properties
    {{
      displayName = {i.name}^N
      description = {i.description}
      radius = {i.radius}
      mass = {i.mass}
      rotates = true
      rotationPeriod = {i.rotationPeriod}{gravityThing}
      tidallyLocked = False
      useTheInName = False
      selectable = True
    }}
    {orbit}
    ScaledVersion
    {{
      Light
      {{
        luminosity = {i.luminosity}
        brightnessCurve
        {{
          key = -0.01573471 0.2 0 0
          key = 0.005 0.2 0 0
          key = 0.01 0 0 0
          key = 0.1 0 0 0
          key = 5.084181 0 0 0
          key = 10 0 0 0
          key = 38.56295 0 0 0
        }}
        IntensityCurve
        {{
          key =	55534 	1.3	0	-5.714E-11
          key =	3500000000 	1.1	-5.714E-11	-4.122E-11
          key =	7000000000 	1.0	-2.061E-11	-2.061E-11
          key =	14000000000 	0.9	-1.030E-11	-1.030E-11
          key =	28000000000 	0.8	-5.152E-12	-5.152E-12
          key =	56000000000 	0.7	-2.576E-12	-2.576E-12
          key =	112000000000 	0.6	-1.288E-12	-1.288E-12
          key =	224000000000 	0.5	-6.441E-13	-6.441E-13
          key =	448000000000 	0.4	-3.220E-13	-3.220E-13
          key =	896000000000 	0.3	-1.610E-13	-1.610E-13
          key =	1792000000000 	0.2	-8.051E-14	-8.051E-14
          key =	3584000000000 	0.1	-4.025E-14	-4.025E-14
          key =	7168000000000 	0	-2.013E-14	0
        }}
        IVAIntensityCurve
        {{
          key =	0 	1.17	0	-5.143E-11
          key =	3500000000 	0.99	-5.143E-11	-3.710E-11
          key =	7000000000 	0.90	-1.855E-11	-1.855E-11
          key =	14000000000 	0.81	-9.274E-12	-9.274E-12
          key =	28000000000 	0.72	-4.637E-12	-4.637E-12
          key =	56000000000 	0.63	-2.319E-12	-2.319E-12
          key =	112000000000 	0.54	-1.159E-12	-1.159E-12
          key =	224000000000 	0.45	-5.797E-13	-5.797E-13
          key =	448000000000 	0.36	-2.898E-13	-2.898E-13
          key =	896000000000 	0.27	-1.449E-13	-1.449E-13
          key =	1792000000000 	0.18	-7.246E-14	-7.246E-14
          key =	3584000000000 	0.09	-3.623E-14	-3.623E-14
          key =   7168000000000 	0	-1.811E-14	0
        }}
        ScaledIntensityCurve
        {{
          key =	0 	1.3	0	-3.429E-07
          key =	583333 	1.1	-3.429E-07	-2.473E-07
          key =	1166667 	1.0	-1.237E-07	-1.237E-07
          key =	2333333 	0.9	-6.183E-08	-6.183E-08
          key =	4666667 	0.8	-3.091E-08	-3.091E-08
          key =	9333333 	0.7	-1.546E-08	-1.546E-08
          key =	18666667 	0.6	-7.729E-09	-7.729E-09
          key =	37333333 	0.5	-3.864E-09	-3.864E-09
          key =	74666667 	0.4	-1.932E-09	-1.932E-09
          key =	149333333 	0.3	-9.661E-10	-9.661E-10
          key =	298666667 	0.2	-4.830E-10	-4.830E-10
          key =	597333333 	0.1	-2.415E-10	-2.415E-10
          key =	1194666667 	0	-1.208E-10	0
        }}
      }}
    }}
    HazardousBody
    {{
      Item
      {{
        ambientTemp = {i.ambientTemp}
        AltitudeCurve
        {{
            key = 1.64E+08 1.00
            key = 3.00E+08 1.00
            key = 4.00E+08 0.80
            key = 7.00E+08 0.60
            key = 1.00E+09 0.40
            key = 1.70E+09 0.20
            key = 2.00E+09 0.15
            key = 4.00E+09 0.10
            key = 5.00E+09 0.05
            key = 6.00E+09 0.00
        }}
      }}
    }}
  }}
}}
''')
